### ISSUE TITLE
Calling functions randomly fails with "Error: Unable to set non-blocking to true"

### ISSUE THREAD

**Issue by sirisian** [brianc/node-libpq#28]
Should this be an error? I'm not 100% sure, but this doesn't seem like it stops the function call from continuing. Seems more like a Notice type message unless I'm misunderstanding the purpose of the error.

**Comment by jakubknejzlik** [comment]
I'm also getting this error, then using pg-native. Can't find the pattern when this happens, but happens too much to use it in production in my case :( (the worst part is that it blocks the whole connection)

**Comment by brianc** [comment]
It would be worth asking around on #postgresql on freenode to see what this error means and if other people hit it from other systems.  I haven't seen this error myself & don't have a reliable way to reproduce it in tests; I'd definitely appreciate it if someone could step up & do some research on this issue if its hitting you.

**Comment by ashish-soni** [comment]
@brianc I am also getting the same error and it appears randomly.

**Comment by brianc** [comment]
Happy to take a pull request to fix this if you're able to narrow it down
to a repeatable thing & write tests for it - I've never seen it myself so
it doesn't really impact me.

**Comment by jeffreyrubi** [comment]
Experienced the same issue in my application. The problem happened occasionally but didn't know a concrete way to repeat it. 

```
2021-02-16T14:47:11.248Z stuka:controller:Runs error invoking a subscription, DatabaseError [SequelizeDatabaseError]: Unable to set non-blocking to true
    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'SequelizeDatabaseError',
  parent: Error: Unable to set non-blocking to true
      at module.exports.Client._dispatchQuery (/app/node_modules/pg-native/index.js:283:27)
      at module.exports.Client.query (/app/node_modules/pg-native/index.js:65:8)
      at module.exports.NativeQuery.submit (/app/node_modules/pg/lib/native/query.js:163:19)
      at module.exports.Client._pulseQueryQueue (/app/node_modules/pg/lib/native/client.js:272:9)
      at module.exports.Client.query (/app/node_modules/pg/lib/native/client.js:223:8)
      at query (/app/node_modules/sequelize/lib/dialects/postgres/query.js:71:53)
      at new Promise (<anonymous>)
      at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:71:9)
      at /app/node_modules/sequelize/lib/sequelize.js:619:28
      at runMicrotasks (<anonymous>) {
    sql: 'SELECT "id", "created_at", "updated_at", "status", "sla_deadline", "dag_version_id" FROM "run" AS "Run" ORDER BY "Run"."id" DESC LIMIT 50 OFFSET 0;',
    parameters: undefined
  },
  original: Error: Unable to set non-blocking to true
      at module.exports.Client._dispatchQuery (/app/node_modules/pg-native/index.js:283:27)
      at module.exports.Client.query (/app/node_modules/pg-native/index.js:65:8)
      at module.exports.NativeQuery.submit (/app/node_modules/pg/lib/native/query.js:163:19)
      at module.exports.Client._pulseQueryQueue (/app/node_modules/pg/lib/native/client.js:272:9)
      at module.exports.Client.query (/app/node_modules/pg/lib/native/client.js:223:8)
      at query (/app/node_modules/sequelize/lib/dialects/postgres/query.js:71:53)
      at new Promise (<anonymous>)
      at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:71:9)
      at /app/node_modules/sequelize/lib/sequelize.js:619:28
      at runMicrotasks (<anonymous>) {
    sql: 'SELECT "id", "created_at", "updated_at", "status", "sla_deadline", "dag_version_id" FROM "run" AS "Run" ORDER BY "Run"."id" DESC LIMIT 50 OFFSET 0;',
    parameters: undefined
  },
  sql: 'SELECT "id", "created_at", "updated_at", "status", "sla_deadline", "dag_version_id" FROM "run" AS "Run" ORDER BY "Run"."id" DESC LIMIT 50 OFFSET 0;',
  parameters: undefined
}
```
