### ISSUE TITLE
Build error when installing on travis

### ISSUE THREAD

**Issue by tomoakley** [brianc/node-libpq#51]
Hi, I'm getting a build error when installing `libpq` on Travis. I'm not using `pq-native` or `libpq` directly; I'm using Sequelize, which I guess implements your packages. Here is the error:

```
make: Leaving directory `/home/travis/build/tomoakley/xysti/node_modules/libpq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-103-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v6.1.0/bin/node" "/home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/tomoakley/xysti/node_modules/libpq
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```

I'm a bit of a newbie to devops/CI so not really sure what you want or need to see to help debug the issue, but happy to provide any info from Travis or my build/code. It's failing on all versions of Node which I have Travis set up to run (0.12, 5, 6, 6.1, stable).

Pretty sure I should be using Docker to do this, however I'm currently just pushing my code to Github which Travis is picking up to run the build.

In my `.travis.yml` file I have Postgres set up:

```
language: node_js

node_js:
  - "0.12"
  - "5"
  - "6"
  - "6.1"
  - "stable"

sudo: required
dist: precise
addons:
    postgresql: "9.5"
services:
    - postgresql

script:
  - npm run lint
  - npm test
```

**Comment by Daniel15** [comment]
Can you provide the `npm-debug.log` file?
