### ISSUE TITLE
bug installing

### ISSUE THREAD

**Issue by ademon82** [brianc/node-libpq#55]
anibal@LENOVO:~/eclipse-workspace/prueba12/WebContent/sequelize$ npm install

> libpq@1.8.7 install /home/anibal/eclipse-workspace/prueba12/WebContent/sequelize/node_modules/libpq
> node-gyp rebuild

find: «/usr/pg*»: No existe el archivo o el directorio
gyp: Call to 'which pg_config || find /usr/bin /usr/local/bin /usr/pg* /opt -executable -name pg_config -print -quit' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.10.0-35-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/anibal/eclipse-workspace/prueba12/WebContent/sequelize/node_modules/libpq
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
sequelize@0.0.0-development /home/anibal/eclipse-workspace/prueba12/WebContent/sequelize
└── (empty)

npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! libpq@1.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libpq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anibal/eclipse-workspace/prueba12/WebContent/sequelize/npm-debug.log
npm ERR! code 1
anibal@LENOVO:~/eclipse-workspace/prueba12/WebContent/sequelize$ npm bugs libpq
anibal@LENOVO:~/eclipse-workspace/prueba12/WebContent/sequelize$ npm -v
3.10.10
anibal@LENOVO:~/eclipse-workspace/prueba12/WebContent/sequelize$ node -v
v6.11.3
anibal@LENOVO:~/eclipse-workspace/prueba12/WebContent/sequelize$

**Comment by ben-turner** [comment]
I'm also seeing this issue. In english: `find: ‘/usr/pg*’: No such file or directory`

**Comment by garcianavalon** [comment]
same here, CI jobs are failing because of this issue

**Comment by jinalex** [comment]
how might we get around this if we're deploying to vercel? I couldn't easily apt-get install on vercel
