### ISSUE TITLE
npm install failes

### ISSUE THREAD

**Issue by LSURENDRAN** [brianc/node-libpq#92]
When I try to install npm i, I am getting below error. Am I missing anything here?

npm ERR! code 1
npm ERR! path /Users/lakshmi/bloomtech/auth/node_modules/libpq
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@19.4.0 | darwin | arm64
npm ERR! gyp http GET https://nodejs.org/download/release/v19.4.0/node-v19.4.0-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: ENOENT: no such file or directory, open '/path/to/DigiCertHighAssuranceEVRootCA.crt'
npm ERR! gyp ERR! stack     at Object.openSync (node:fs:584:3)
npm ERR! gyp ERR! stack     at Object.readFileSync (node:fs:452:35)
npm ERR! gyp ERR! stack     at readCAFile (/Users/lakshmi/bloomtech/auth/node_modules/node-gyp/lib/install.js:472:15)
npm ERR! gyp ERR! stack     at download (/Users/lakshmi/bloomtech/auth/node_modules/node-gyp/lib/install.js:444:22)
npm ERR! gyp ERR! stack     at /Users/lakshmi/bloomtech/auth/node_modules/node-gyp/lib/install.js:189:19
npm ERR! gyp ERR! stack     at /Users/lakshmi/bloomtech/auth/node_modules/node-gyp/node_modules/mkdirp/index.js:51:26
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:191:5)
npm ERR! gyp ERR! System Darwin 22.2.0
npm ERR! gyp ERR! command "/Users/lakshmi/.nvm/versions/node/v19.4.0/bin/node" "/Users/lakshmi/bloomtech/auth/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/lakshmi/bloomtech/auth/node_modules/libpq
npm ERR! gyp ERR! node -v v19.4.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lakshmi/.npm/_logs/2023-02-17T19_04_55_960Z-debug-0.log

Thanks,
Lakshmi

**Comment by yuriitaran** [comment]
I ran into the same issue installing libpq and managed to solve it by running `apt-get install libpq-dev g++ make`
More info is [here](https://github.com/brianc/node-pg-native#install).

**Comment by nrathi** [comment]
@LSURENDRAN were you able to fix this?

**Comment by brianc** [comment]
https://github.com/brianc/node-libpq/issues/85#issuecomment-1279702249

more info here, too

**Comment by airtonix** [comment]
It's pretty scary that this highly relied on library is so fraught with install issues
